exports.basePath = "src/main/resources"
exports.srcPath = exports.basePath + "/frontend"
exports.buildPath = exports.basePath + "/static"
exports.testPath = "src/test/resources"
exports.testSrcPath = "src/test/*.ts"
